'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { ArrowUpRight, BarChart3, Bell, ChevronRight, CircleHelp, FileText, Hash, Inbox, LayoutDashboard, Plus, Settings, Sparkles, WandSparkles } from 'lucide-react'

const nav = [{ href: '/', label: 'Overview', icon: LayoutDashboard }, { href: '/create', label: 'Input studio', icon: WandSparkles }, { href: '/queue', label: 'Approval queue', icon: Inbox }]

export function Shell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname()
  return <div className="min-h-screen bg-[#08090b] text-zinc-100"><aside className="fixed inset-y-0 left-0 hidden w-[224px] border-r border-white/[.07] bg-[#0b0c0f] px-4 py-5 lg:flex lg:flex-col"><Link href="/" className="mb-10 flex items-center gap-2 px-2"><span className="grid size-7 place-items-center rounded-lg bg-lime-300 text-black"><Sparkles size={15} /></span><span className="text-[15px] font-semibold tracking-tight">orbit<span className="text-lime-300">.</span></span></Link><p className="px-2 pb-3 text-[10px] font-semibold uppercase tracking-[.18em] text-zinc-500">Workspace</p><nav className="flex flex-col gap-1">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`flex items-center justify-between rounded-lg px-3 py-2.5 text-sm ${pathname === href ? 'bg-white/[.08] text-white' : 'text-zinc-500 hover:bg-white/[.04] hover:text-zinc-200'}`}><span className="flex items-center gap-3"><Icon size={16} />{label}</span>{href === '/queue' && <span className="rounded bg-lime-300 px-1.5 py-0.5 text-[10px] font-bold text-black">3</span>}</Link>)}</nav><div className="mt-auto flex flex-col gap-1 border-t border-white/[.07] pt-4"><Link href="#" className="flex items-center gap-3 px-3 py-2 text-sm text-zinc-500"><BarChart3 size={16} />Analytics</Link><Link href="#" className="flex items-center gap-3 px-3 py-2 text-sm text-zinc-500"><Settings size={16} />Settings</Link><div className="mt-4 flex items-center gap-3 rounded-lg bg-white/[.04] p-2.5"><div className="grid size-8 place-items-center rounded-full bg-gradient-to-br from-lime-300 to-cyan-300 text-xs font-bold text-black">JD</div><div className="min-w-0"><p className="truncate text-xs font-medium">Jordan Davis</p><p className="truncate text-[10px] text-zinc-500">Pro workspace</p></div><ChevronRight size={14} className="ml-auto text-zinc-600" /></div></div></aside><div className="lg:pl-[224px]"><header className="flex h-16 items-center justify-between border-b border-white/[.07] px-5 sm:px-8"><div className="flex items-center gap-2 text-xs text-zinc-500"><span className="size-1.5 rounded-full bg-lime-300" /> All systems operational</div><div className="flex items-center gap-4"><button aria-label="Notifications" className="text-zinc-500 hover:text-white"><Bell size={17} /></button><button className="flex items-center gap-2 text-xs text-zinc-400"><CircleHelp size={16} /> Help center</button></div></header><main className="mx-auto max-w-[1240px] px-5 py-8 sm:px-8">{children}</main></div></div>
}

export default function Page() { return <Shell><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-medium uppercase tracking-[.18em] text-lime-300">Monday, September 15, 2026</p><h1 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Good morning, Jordan.</h1><p className="mt-2 text-sm text-zinc-500">Your content engine is ready when you are.</p></div><Link href="/create" className="inline-flex items-center justify-center gap-2 rounded-lg bg-lime-300 px-4 py-2.5 text-sm font-semibold text-black transition hover:bg-lime-200"><Plus size={17} /> Create new draft</Link></div><div className="grid gap-3 sm:grid-cols-3"><Stat label="Pending approval" value="03" detail="Ready for your review" accent /><Stat label="Published this month" value="18" detail="Across 4 platforms" /><Stat label="Avg. engagement" value="8.4%" detail="↑ 1.2% vs last month" /></div><div className="mt-10 grid gap-5 xl:grid-cols-[1.45fr_1fr]"><section className="rounded-xl border border-white/[.08] bg-[#0d0f12] p-5 sm:p-6"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-zinc-500">Quick start</p><h2 className="mt-1 text-lg font-medium">Turn an idea into a campaign</h2></div><Sparkles size={20} className="text-lime-300" /></div><div className="grid gap-3 sm:grid-cols-3"><Quick href="/create" icon={WandSparkles} title="Generate drafts" text="Start from a topic or script." /><Quick href="/queue" icon={Inbox} title="Review queue" text="Approve your next posts." /><Quick href="#" icon={Hash} title="Brand voice" text="Manage your guidelines." /></div></section><section className="rounded-xl border border-white/[.08] bg-[#0d0f12] p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-zinc-500">Recent activity</p><h2 className="mt-1 text-lg font-medium">What&apos;s moving</h2></div><ArrowUpRight size={17} className="text-zinc-600" /></div><div className="flex flex-col gap-4"><Activity text="Draft generated" detail="The future of remote work" time="8m ago" color="bg-lime-300" /><Activity text="Published to LinkedIn" detail="Building in public: week 4" time="2h ago" color="bg-cyan-300" /><Activity text="Draft edited" detail="Three habits for better focus" time="Yesterday" color="bg-violet-300" /></div></section></div></Shell> }
function Stat({ label, value, detail, accent }: { label: string; value: string; detail: string; accent?: boolean }) { return <div className={`rounded-xl border p-5 ${accent ? 'border-lime-300/25 bg-lime-300/[.06]' : 'border-white/[.08] bg-[#0d0f12]'}`}><p className="text-xs text-zinc-500">{label}</p><p className={`mt-3 text-3xl font-semibold tracking-[-.04em] ${accent ? 'text-lime-300' : 'text-white'}`}>{value}</p><p className="mt-1 text-xs text-zinc-600">{detail}</p></div> }
function Quick({ href, icon: Icon, title, text }: { href: string; icon: typeof Plus; title: string; text: string }) { return <Link href={href} className="group rounded-lg border border-white/[.07] bg-white/[.02] p-4 transition hover:border-lime-300/30 hover:bg-lime-300/[.04]"><Icon size={18} className="text-lime-300" /><p className="mt-8 text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-5 text-zinc-500">{text}</p></Link> }
function Activity({ text, detail, time, color }: { text: string; detail: string; time: string; color: string }) { return <div className="flex items-start gap-3"><span className={`mt-1.5 size-2 rounded-full ${color}`} /><div className="min-w-0 flex-1"><p className="text-sm">{text}</p><p className="truncate text-xs text-zinc-500">{detail}</p></div><span className="text-[11px] text-zinc-600">{time}</span></div> }
